"""DB Migration

Revision ID: a2058df07662
Revises: 
Create Date: 2022-06-11 01:24:19.426495

"""
import bcrypt
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from db.dbModel import UserRoles, User

revision = 'a2058df07662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('col1', sa.Integer(), nullable=True),
    sa.Column('col2', sa.String(), nullable=True),
    sa.Column('col3', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'job_id')
    )
    op.create_index(op.f('ix_data_id'), 'data', ['id'], unique=False)
    op.create_index(op.f('ix_data_job_id'), 'data', ['job_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    list_user_roles = op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), autoincrement=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.bulk_insert(list_user_roles, [
        {'role_id': 0, 'title': 'admin'},
        {'role_id': 1, 'title': 'data'},
        {'role_id': 2, 'title': 'viewer'},
        {'role_id': 3, 'title': 'qc'}
    ])
    list_users = op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    admin_pass = bcrypt.hashpw('admin123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    op.bulk_insert(list_users, [
        {
            'email': 'admin@earthify.com',
            'password': admin_pass,
            'first_name': 'System',
            'last_name': 'Admin',
            'role_id': 0
        }
    ])
    # op.drop_table('spatial_ref_sys')
    # seed()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_data_job_id'), table_name='data')
    op.drop_index(op.f('ix_data_id'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###


def seed() -> None:
    op.bulk_insert(UserRoles.__tablename__, [
        {'role_id': 0, 'title': 'admin'},
        {'role_id': 1, 'title': 'data'},
        {'role_id': 2, 'title': 'viewer'},
        {'role_id': 3, 'title': 'qc'}
    ])
    admin_pass = bcrypt.hashpw('admin123'.encode('utf-8'), bcrypt.gensalt())
    admin_pass = admin_pass.decode('utf-8')
    op.bulk_insert(User.__tablename__, [
        {
            'email': 'admin@earthify.com',
            'password': admin_pass,
            'first_name': 'System',
            'last_name': 'Admin',
            'role_id': 0
        }
    ])
